/** @type {import('tailwindcss').Config} */
module.exports = {
  // content: [''],
  corePlugins: {
    components: true,
  },
  theme: {
    extend: {
      colors: {
        primary: '#409eff',
        primary_light_3: '#79bbff',
        primary_light_5: '#a0cfff',
        primary_light_7: '#c6e2ff',
        primary_light_8: '#d9ecff',
        primary_light_9: '#ecf5ff',
        success: '#67c23a',
        success_light_3: '#95d475',
        success_light_5: '#b3e19d',
        success_light_7: '#d1edc4',
        success_light_8: '#e1f3d8',
        success_light_9: '#f0f9eb',
        wraning: '#e6a23c',
        wraning_light_3: '#eebe77',
        wraning_light_5: '#f3d19e',
        wraning_light_7: '#f8e3c5',
        wraning_light_8: '#faecd8',
        wraning_light_9: '#fdf6ec',
        danger: '#f56c6c',
        danger_light_3: '#f89898',
        danger_light_5: '#fab6b6',
        danger_light_7: '#fcd3d3',
        danger_light_8: '#fde2e2',
        danger_light_9: '#fef0f0',
        error: '#f56c6c',
        error_light_3: '#f89898',
        error_light_5: '#fab6b6',
        error_light_7: '#fcd3d3',
        error_light_8: '#fde2e2',
        error_light_9: '#fef0f0',
        info: '#909399',
        info_light_3: '#b1b3b8',
        info_light_5: '#c8c9cc',
        info_light_7: '#dedfe0',
        info_light_8: '#e9e9eb',
        info_light_9: '#f4f4f5',
        color_primary: '#303133',
        color_regular: '#606266',
        color_secondary: '#909399',
        color_placeholder: '#a8abb2',
        color_disabled: '#c0c4cc',
        /***/
        border_color: '#dcdfe6',
        border_color_dark: '#d4d7de',
        border_color_darker: '#cdd0d6',
        border_color: '#dcdfe6',
        border_color_light: '#e4e7ed',
        border_color_lighter: '#ebeef5',
        border_color_extra_light: '#f2f6fc',
        /** */
        fill_color: '#f0f2f5',
        fill_color_light: '#f5f7fa',
        fill_color_lighter: '#fafafa',
        fill_color_extra_light: '#fafcff',
        fill_color_dark: '#ebedf0',
        fill_color_darker: '#e6e8eb',
        fill_color_blank: '#ffffff',
        font_size_extra_large: '20px',
        font_size_large: '18px',
        font_size_medium: '16px',
        font_size_base: '14px',
        font_size_small: '13px',
        font_size_extra_small: '12px',
        font_weight_primary: '500',
        font_line_height_primary: '24px',
        index_normal: '1',
        index_top: '1000',
        index_popper: '2000',
        transition_duration: '0.3s',
        transition_duration_fast: '0.2s',
        transition_function_ease_in_out_bezier: '',
      },
    },
    screens: {
      xs: { max: '768px' },
    },
  },
  plugins: [],
};
